// "use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import ThemeWrapper from "@/Components/ThemeWrapper";
import ClientProviders from "@/Components/ClientProviders"; 

// import useThemeStore from "../store/useThemeStore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { theme } = useThemeStore();

  return (
    // data-theme={"light"}
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeWrapper>
          <Navbar />
          <ClientProviders>{children}</ClientProviders>
        </ThemeWrapper>
      </body>
    </html>
  );
}
